# Generated by Django 4.0.1 on 2022-01-18 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciplan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(default='deku nuts', max_length=100),
            preserve_default=False,
        ),
    ]
