# Generated by Django 4.0.1 on 2022-02-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciplan', '0004_remove_recipe_ingredients_recipe_directions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='in_cart',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='cup_amt',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='unit_of_measure',
            field=models.CharField(choices=[('fl_oz', 'fl oz'), ('fl_cups', 'fl cups'), ('cups', 'cups'), ('pints', 'pints'), ('quarts', 'quarts'), ('gallons', 'gallons'), ('tsp', 'tsp'), ('Tbsp', 'Tbsp'), ('grams', 'grams'), ('Kg', 'Kg'), ('oz', 'oz'), ('lbs', 'lbs'), ('mL', 'mL'), ('liters', 'liters'), ('ea', 'ea')], max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to='reciplan/images/'),
        ),
    ]
