# Generated by Django 4.0.1 on 2022-02-06 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reciplan', '0006_alter_ingredients_cup_amt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='cup_amt',
        ),
    ]
