# Generated by Django 4.0.1 on 2022-02-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciplan', '0007_remove_ingredients_cup_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='cup_amt',
            field=models.FloatField(null=True),
        ),
    ]
