# Generated by Django 4.0.1 on 2022-02-23 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reciplan', '0009_alter_ingredients_amt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='cup_amt',
        ),
    ]
